// Video URLs - auto-generated by upload-videos-to-blob.ts

export const VIDEO_URLS = {
  heroLoop: "",
  heroPoster: "",
  complianceShield: "",
  reconaiPreview: "",
} as const;

// Helper to get video URL with fallback to local path
export function getVideoUrl(
  key: keyof typeof VIDEO_URLS,
  localFallback: string
): string {
  return VIDEO_URLS[key] || localFallback;
}
