// Video URLs - auto-generated by upload-videos-to-blob.ts

export const VIDEO_URLS = {
  heroLoop:
    "https://5exbqzond8olwl0z.public.blob.vercel-storage.com/videos/hero-loop.mp4",
  heroPoster:
    "https://5exbqzond8olwl0z.public.blob.vercel-storage.com/videos/hero-poster.webp",
  complianceShield:
    "https://5exbqzond8olwl0z.public.blob.vercel-storage.com/videos/compliance-shield-loop.mp4",
  reconaiPreview:
    "https://5exbqzond8olwl0z.public.blob.vercel-storage.com/videos/reconai-preview.mp4",
} as const;

// Helper to get video URL with fallback to local path
export function getVideoUrl(
  key: keyof typeof VIDEO_URLS,
  localFallback: string,
): string {
  return VIDEO_URLS[key] || localFallback;
}
