import { put } from "@vercel/blob";
import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

const VIDEOS_DIR = join(process.cwd(), "public", "videos");

const videos = [
  { name: "hero-loop.mp4", contentType: "video/mp4" },
  { name: "hero-poster.webp", contentType: "image/webp" },
  { name: "compliance-shield-loop.mp4", contentType: "video/mp4" },
  { name: "reconai-preview.mp4", contentType: "video/mp4" },
];

async function uploadVideos() {
  const urls: Record<string, string> = {};

  for (const video of videos) {
    const filePath = join(VIDEOS_DIR, video.name);
    console.log(`Uploading ${video.name}...`);

    try {
      const fileBuffer = readFileSync(filePath);
      const blob = await put(`videos/${video.name}`, fileBuffer, {
        access: "public",
        contentType: video.contentType,
      });

      urls[video.name] = blob.url;
      console.log(`✓ Uploaded: ${blob.url}`);
    } catch (error) {
      console.error(`✗ Failed to upload ${video.name}:`, error);
    }
  }

  // Save URLs to a config file
  const configPath = join(process.cwd(), "src", "config", "video-urls.ts");
  const configContent = `// Video URLs - auto-generated by upload-videos-to-blob.ts

export const VIDEO_URLS = {
  heroLoop: "${urls["hero-loop.mp4"] || ""}",
  heroPoster: "${urls["hero-poster.webp"] || ""}",
  complianceShield: "${urls["compliance-shield-loop.mp4"] || ""}",
  reconaiPreview: "${urls["reconai-preview.mp4"] || ""}",
} as const;

// Helper to get video URL with fallback to local path
export function getVideoUrl(
  key: keyof typeof VIDEO_URLS,
  localFallback: string
): string {
  return VIDEO_URLS[key] || localFallback;
}
`;

  writeFileSync(configPath, configContent);
  console.log(\`\\n✓ Config saved to \${configPath}\`);
}

uploadVideos().catch(console.error);
