import { LegalPage } from "@/components/legal/legal-page";

export default function TermsOfServicePage() {
  return (
    <LegalPage title="Terms of Service" updated="2026-01-09">
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use
        of the ReconAI platform, website, and related services (collectively,
        the &quot;Services&quot;). The Services are operated by{" "}
        <strong>[COMPANY_LEGAL_NAME]</strong> (&quot;ReconAI&quot;,
        &quot;we&quot;, &quot;us&quot;, or &quot;our&quot;). By creating an
        account, accessing, or using the Services, you agree to be bound by
        these Terms.
      </p>

      <h2>1. Eligibility and Accounts</h2>
      <ul>
        <li>You must be at least 18 years old to use the Services.</li>
        <li>
          You are responsible for maintaining the confidentiality of your login
          credentials and for all activity under your account.
        </li>
        <li>
          You agree to provide accurate information and keep your account
          details up to date.
        </li>
      </ul>

      <h2>2. What ReconAI Is (and Is Not)</h2>
      <p>
        ReconAI provides tools that help users organize, analyze, and understand
        financial information. ReconAI is
        <strong> not a bank</strong>, <strong>not a CPA</strong>,{" "}
        <strong>not an accountant</strong>, <strong>not a tax advisor</strong>,
        and
        <strong> not a law firm</strong>. Any insights, classifications,
        summaries, or recommendations generated by the Services (including any
        AI-assisted output) are provided for informational purposes only.
      </p>
      <p>
        You are solely responsible for verifying outputs and making decisions
        based on your circumstances. You should consult qualified professionals
        (e.g., financial, tax, legal) before making decisions.
      </p>

      <h2>3. AI-Assisted Features and Limitations</h2>
      <ul>
        <li>
          AI-assisted outputs may be incomplete, inaccurate, or unsuitable for
          your specific situation.
        </li>
        <li>
          Classifications and categorizations are probabilistic and require
          human review.
        </li>
        <li>
          You agree not to rely on AI outputs as the sole basis for any
          financial, tax, legal, or business decision.
        </li>
      </ul>

      <h2>4. Third-Party Services (Plaid and Others)</h2>
      <p>
        The Services may integrate with third-party providers to help you
        connect financial accounts and retrieve data. For example, we may use
        Plaid Inc. (&quot;Plaid&quot;) to facilitate secure connections to your
        financial institutions. Your use of third-party providers may be subject
        to their separate terms and privacy practices. We are not responsible
        for third-party services.
      </p>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>
          Use the Services for unlawful, fraudulent, or deceptive purposes.
        </li>
        <li>Attempt to gain unauthorized access to systems or data.</li>
        <li>
          Interfere with or disrupt the Services, including by transmitting
          malware or abusive traffic.
        </li>
        <li>
          Reverse engineer, scrape, or harvest the Services except as permitted
          by law.
        </li>
        <li>
          Use the Services to violate the rights of others or applicable
          regulations.
        </li>
      </ul>

      <h2>6. Intellectual Property</h2>
      <p>
        The Services, including software, text, graphics, logos, and design
        elements, are owned by ReconAI or our licensors and are protected by
        intellectual property laws. You receive a limited, non-exclusive,
        non-transferable license to use the Services for your internal purposes,
        subject to these Terms.
      </p>

      <h2>7. User Content</h2>
      <p>
        You may provide data, files, or information to the Services (&quot;User
        Content&quot;). You retain ownership of your User Content. You grant
        ReconAI a limited license to process your User Content to provide and
        improve the Services, including generating reports and analytics for
        you.
      </p>

      <h2>8. Service Availability and Changes</h2>
      <p>
        We may modify, suspend, or discontinue all or part of the Services at
        any time. We do not guarantee uninterrupted operation. Maintenance
        windows may occur.
      </p>

      <h2>9. Disclaimers</h2>
      <p>
        THE SERVICES ARE PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot;
        WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WARRANTIES
        OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
        NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICES WILL BE ERROR-FREE
        OR SECURE.
      </p>

      <h2>10. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, RECONAI WILL NOT BE LIABLE FOR
        INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR
        ANY LOSS OF PROFITS, REVENUE, DATA, OR GOODWILL, ARISING FROM OR RELATED
        TO YOUR USE OF THE SERVICES.
      </p>

      <h2>11. Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless ReconAI from claims,
        liabilities, damages, and expenses (including reasonable attorneys&apos;
        fees) arising from your use of the Services, your User Content, or your
        violation of these Terms.
      </p>

      <h2>12. Governing Law</h2>
      <p>
        These Terms are governed by the laws of the jurisdiction where ReconAI
        is organized and operates, without regard to conflict-of-law principles,
        unless applicable law requires otherwise.
      </p>

      <h2>13. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. If we make material
        changes, we will provide notice as required by law. Continued use of the
        Services after changes become effective constitutes acceptance.
      </p>

      <h2>14. Contact</h2>
      <p>
        Questions about these Terms can be directed to:{" "}
        <strong>[CONTACT_EMAIL]</strong>.
      </p>
    </LegalPage>
  );
}
